test:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Dependencies
      run: composer install

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: Create SQLite DB
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Migration
      run: php artisan migrate --force

    - name: Run Test
      run: php artisan test